spring:
  datasource:
    username: root
    password: zx123456
    url: jdbc:mysql://localhost:3306/gulimall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-ware
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: 192.168.23.101
    port: 5672
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
      # 手动开启ack确认小消息
    listener:
      direct:
        acknowledge-mode: manual
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 11000
logging:
  level:
    com.atguigu: debug
